# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e5d3e8a5c8f2a525c1819dd212209156b396acdda04b29f95efb30371bf5561d594d795a939d97dc55e4a5e5eb0855b9460acec6a876f4309b38fec67286519

test:
  secret_key_base: b07ff0d65db3818b386caac47f4e23182cc4e49435bf794efcd6df8b9241e4917cbf88fd785c33628ba0418b92c407a9125c98f3b263a29de484be701944807f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
